### ISSUE TITLE
Correct RMSE to be mean square error not absolute square error

### ISSUE THREAD

**Issue by katielukow** [pybop-team/PyBOP#106]
### Feature description

[Cost function for root mean square error](https://github.com/pybop-team/PyBOP/blob/c8bd36cfe8879bbc9e03d5f103ef1225ccd66139/pybop/costs/error_costs.py#L44C30-L44C30) is calculating just root square error. Needs to be divided by n before square root to be rmse. 
[
Julia reference.](https://juliastats.org/StatsBase.jl/stable/deviation/)

### Motivation

RMSE definition is incorrect

**Comment by BradyPlanden** [comment]
We use numpy.mean to capture the $1/n$ component of this cost function. Marking complete.
