### ISSUE TITLE
Add PyBaMM version matrix to scheduled tests

### ISSUE THREAD

**Issue by BradyPlanden** [pybop-team/PyBOP#123]
### Feature description

Add a testing matrix of the most recent pybamm versions to the scheduled daily workflow. The last four releases is probably a good place to start. This should only be added to the most recent python version to avoid clashes.

### Motivation

Provides us with a range of supported pybamm versions and should improve ease-of-use for end-users.

**Comment by agriyakhetarpal** [comment]
Just to clarify – as mentioned in the comment, each PyBaMM version should correspond to a Python version? Or did you mean testing all four PyBaMM versions with the latest Python version?

This should be doable by checking out the PyBaMM repository from a particular tag and building it from source. The PyPI wheels corresponding to a version can be used directly too, as long as we have support for required platforms and architectures (should be all except M-series macOS).

**Comment by BradyPlanden** [comment]
Hi Agriya, 

Good question, I hadn't fleshed out the concept much in the original post. The goal is to ensure that a list of recent pybamm versions is supported within pybop. Ideally this would allow us to relax the pybamm version constraint and/or have a metric to decide when to bump the dependency. 

Creating an implementation for the latest Python and building from source (or wheels, if applicable) sounds like a good compromise between test time and coverage. That said, I'm not opposed to testing against the Python matrix we currently have in the scheduled tests.

**Comment by agriyakhetarpal** [comment]
Testing against the Python matrix, even though it would consume a lot of parallel jobs (four PyBaMM versions per Python version), sounds like the best way to go forward with.

We can do both things: use the wheels for now while building from source for M-series. We may switch to using the wheels for everything when I finish https://github.com/pybamm-team/PyBaMM/issues/3772.
