### ISSUE TITLE
Add experimental data for ECM fitting

### ISSUE THREAD

**Issue by BradyPlanden** [pybop-team/PyBOP#170]
### Feature description

Potential datasets:

https://github.com/HVES-Battery-Testing-Consortium/LG-HG2
https://github.com/Battery-Intelligence-Lab/BatEst/tree/main/Data/Examples

**Comment by NicolaCourtier** [comment]
Suggestion from @WDWidanage:

"Here is some data on the LGM50: https://github.com/WDWidanage/Simscape-Battery-Library/tree/main/Examples/parameterEstimation_TECMD/Data
It has
- OCV,
- Pulse/HPPC
- Rate tests

At four temperatures (0-45degC) and four C-rates (from 0.1C-2C) . The file size is also small (2.64MB) which is good for git."
