### ISSUE TITLE
[Bug]: ElectrodeSOH implementation doesn't update `Q_Li`

### ISSUE THREAD

**Issue by BradyPlanden** [pybop-team/PyBOP#339]
### Python Version

N/A

### Describe the bug

- electodeSOH in echem models doesn't update Q_Li in the pybamm_model. 
- This causes issues in the design cost functions as they commonly modify electrode capacity parameters
- [pybamm code ref](https://github.com/pybamm-team/PyBaMM/blob/a553fe6b980abfdb560263be78d72ad534d25419/pybamm/models/full_battery_models/lithium_ion/electrode_soh.py#L535)

### Steps to reproduce the behaviour

run:
```bash
python examples/scripts/spme_max_energy.py
```

Grey areas are cost values of np.inf, which can be a result of `Q_p` > `Q_Li`.

**Comment by NicolaCourtier** [comment]
To see a grey area, change the design parameters to e.g.
```
parameters = pybop.Parameters(
    pybop.Parameter(
        "Positive electrode thickness [m]",
        prior=pybop.Gaussian(7.56e-05, 0.1e-05),
        bounds=[65e-06, 10e-05],
    ),
    pybop.Parameter(
        "Negative electrode thickness [m]",
        prior=pybop.Gaussian(7.56e-05, 0.1e-05),
        bounds=[65e-06, 10e-05],
    ),
)
```
