### ISSUE TITLE
Notebook "multi_optimiser_identification" - class Parameter

### ISSUE THREAD

**Issue by L0tusC00kie** [pybop-team/PyBOP#376]
Hi,
while using the notebook named above I notice following issues/errors. Some of which I can fix by adjusting arguments as described in documentation and some I cannot. 

- **module 'pybop.models.lithium_ion' has no attribute 'DFN'** : According to documentation, pybop.models.lithium_ion now only supports SPM/SPMe/echem_base

- **module 'pybop' has no attribute 'Parameters'**: It's just Parameter, with no 's'

- **pybop does not take AdamW and NelderMead as Optimisers**: I just remove them from the list of Optimsers

Here's the  biggest issue when I try to define the FittingProblem with problem = pybop.FittingProblem(model, parameters, dataset, init_soc=init_soc). I get this error message

 **object of type 'Parameter' has no len()**

I have read the source code of class Parameter and found no sign of len() Function. Another try in Colab returns the same error with a little bit more detailed message 

![image](https://github.com/pybop-team/PyBOP/assets/169990176/820c32d6-275d-4a0d-9832-f042913cb7a4)

Has anyone encountered this too and can help me with some insights?
Thanks in advance!

**Comment by BradyPlanden** [comment]
Hi @L0tusC00kie, 

We are currently in between releases, and have had a larger amount of API changes than previous releases. For the time being, the examples will work if you install from `develop` as described below.

```python
pip install git+https://github.com/pybop-team/PyBOP.git@develop
```

Do let me know if you have any further issues.
