### ISSUE TITLE
Add Thermal Thevenin Example (Remove Params from Others)

### ISSUE THREAD

**Issue by BradyPlanden** [pybop-team/PyBOP#437]
This issue is to remove the thermal parameters from non-thermal Thevenin examples: https://github.com/pybop-team/PyBOP/blob/9e15f90b75c4f5fb04cb17c0807dd0b5e1a2e6fb/examples/scripts/ecm_CMAES.py#L24

At the sametime, let's add a Thevenin with thermal submodel example with those corresponding parameters. For more information on PyBaMM's thermal submodel see: https://docs.pybamm.org/en/latest/source/examples/notebooks/models/thermal-models.html

**Comment by BradyPlanden** [comment]
@Dibyendu-IITKGP, are you be able to take this one on?

**Comment by Dibyendu-IITKGP** [comment]
Not yet. I'll do it.
