### ISSUE TITLE
[Bug]: multi_model_identification.ipynb shows incorrect results

### ISSUE THREAD

**Issue by NicolaCourtier** [pybop-team/PyBOP#446]
### Python Version

3.11

### Describe the bug

The figures in the `multi_model_identification.ipynb` example notebook are not correct because the initial parameter values are not reset before the second optimisation.

Fixed by #425 in the next release.

### Steps to reproduce the behaviour

Review the `multi_model_identification.ipynb` notebook.

**Comment by BradyPlanden** [comment]
Closing as this was fixed in #425.
