### ISSUE TITLE
[Bug]: spm_electrode_design.ipynb not producing correct results

### ISSUE THREAD

**Issue by NicolaCourtier** [pybop-team/PyBOP#447]
### Python Version

3.11

### Describe the bug

The figures in the `spm_electrode_design.ipynb` example notebook are not correct because the initial concentrations are not set in a consistent way.

Fixed by #425 in the next release.

### Steps to reproduce the behaviour

Review the  `spm_electrode_design.ipynb` notebook.

**Comment by BradyPlanden** [comment]
Closing as this was fixed in #425.
