### ISSUE TITLE
[Bug]: Release v24.9.0 broken

### ISSUE THREAD

**Issue by BradyPlanden** [pybop-team/PyBOP#494]
### Python Version

3.12

### Describe the bug

v24.9.0 is currently broken due to the optional `pybamm[cite]` dependency. The open issue on the PyBaMM repo [is here](https://github.com/pybamm-team/PyBaMM/issues/4432). 

We can either yank this release or release v24.9.1 with the optional dependency removed. This proceeds with a warning on import instead of an error. @NicolaCourtier  @martinjrobins @brosaplanella @agriyakhetarpal  Any preferences? I think patching to `v24.9.1` is probably mine.

### Steps to reproduce the behaviour

`pip install pybop`
`import pybop`

**Comment by agriyakhetarpal** [comment]
Thanks for the ping, @BradyPlanden! Yanking the release sounds better to me, since PyBOP is unusable with PyBaMM v24.9.0 in this case. PyBOP v24.9.1 can be released afterwards when PyBaMM is ready.

**Comment by BradyPlanden** [comment]
Fair shout - I've yanked it now.
