### ISSUE TITLE
Point parameter estimation methods

### ISSUE THREAD

**Issue by BradyPlanden** [pybop-team/PyBOP#5]
Overarching parent issue to cover the family of all methods that give only "point" parameter estimates (rather than distributions) - i.e., maximum likelihood estimation (MLE) including variations such as prediction error minimisation (PEM); maximum a posteriori (MAP) estimation.

**Comment by martinjrobins** [comment]
in terms of a method to get the point estimate, CMAES is a pretty reliable method (again lots of implementations including PINTS ;)

**Comment by davidhowey** [comment]
interesting; we should have a deep dive discussion on all this. We have tended previously just to use variants of [BFGS](https://en.wikipedia.org/wiki/Broyden–Fletcher–Goldfarb–Shanno_algorithm)

**Comment by BradyPlanden** [comment]
We have added quite a few frequentistic [methods](https://github.com/pybop-team/PyBOP/tree/develop/pybop/optimisers), closing this issue.
