### ISSUE TITLE
[Bug]:  cannot import name 'greycomatrix' from 'skimage.feature'

### ISSUE THREAD

**Issue by JulWilh** [pybop-team/PyBOP#518]
### Python Version

3.9.4

### Describe the bug

Hey all, 
I tried to import pybob with "import pybob" resulting in ImportError: cannot import name 'greycomatrix' from 'skimage.feature'. 

Package versions: 
pybob 0.26.2 
scikit-image 0.24.0

### Steps to reproduce the behaviour

Run "import pybob" with python

### Relevant log output

```shell
import pybob
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[MyFolder]\pybob\__init__.py", line 5, in <module>
    from . import image_tools
  File "[MyFolder]\pybob\image_tools.py", line 16, in <module>
    from skimage.feature import greycomatrix, greycoprops
ImportError: cannot import name 'greycomatrix' from 'skimage.feature'
```

**Comment by JulWilh** [comment]
I can do: from skimage.feature import graycomatrix, graycoprops

Is there a typo in the code or am I'm doing something wrong?

**Comment by agriyakhetarpal** [comment]
Hi @JulWilh, this repository tracks the development for `pybop`, and not `pybob` (`p` vs `b`). This issue looks like it's better suited for opening under https://github.com/iamdonovan/pybob. :)

Side note: yes, I think `scikit-image` changed their instances of `grey` to `gray` across all their spellings some time down the line in their development.

**Comment by JulWilh** [comment]
Thanks. That was a stupid typo by myself.

**Comment by agriyakhetarpal** [comment]
No worries at all, happens to the best of us!
