### ISSUE TITLE
Allow linked parameter updates for design optimisation

### ISSUE THREAD

**Issue by NicolaCourtier** [pybop-team/PyBOP#532]
### Feature description

Allow optimisation parameters to update other model parameters via custom, user-defined functions.

### Motivation

To enable the optimisation of linked parameters. For example, allowing users to optimise the active material volume fraction, while updating the porosity so that their sum equals one.

### Possible implementation

This is easier to do for design optimisation due to the use of `model.predict`, which takes an updated `parameter_set` in `DesignProblem.evaluate`.

**Comment by BradyPlanden** [comment]
This sounds great @NicolaCourtier, it would be great to implement this for both `FittingProblem` as well as `DesignProblem`, do you think that can be within scope of this issue? It could help reduce the number of infeasible solutions the optimisers experience during identification 😃

**Comment by NicolaCourtier** [comment]
Thanks Brady, we are working on it! Hopefully it can be the same implementation for all problem types.
