### ISSUE TITLE
Hamiltonian Monte Carlo (HMC)

### ISSUE THREAD

**Issue by BradyPlanden** [pybop-team/PyBOP#6]
The [No-U-Turn ](https://arxiv.org/pdf/1111.4246v1.pdf) Hamiltonian Monte Carlo (HMC) method provide a robust method to capture a posterior distributions with efficient sampling and adaptive step size selection. Capturing the parameter posterior distributions for $\varepsilon = (\hat{y} - y$). This issue surmises the following:

- Integrate a NUTS implementation from a common, well-supported probablistic library
- Build corresponding test suite with code coverage
- Build diagonostics from posterior distribution (i.e. parameter observability) as well as performance-based metrics.

**Comment by martinjrobins** [comment]
HMC (or NUTS is the varient always used in practice) is great. But for low numbers of parameters a simple method like Adaptive Covariance can be more reliable. Either way, loads of libraries give you NUTS and Adaptive Covariance (like PINTS ;) ) so I think getting both of these will be easy
