### ISSUE TITLE
Add run-tests.py

### ISSUE THREAD

**Issue by NicolaCourtier** [pybop-team/PyBOP#61]
### Feature description

A request to add the `run-tests.py` script for developers who are not using nox to run the tests.

**Comment by BradyPlanden** [comment]
Hi Nicola, here's a solution to the testing suite without the nox environment:

`pytest --unit` or `python -m pytest --unit`

For parallelised runs, [pytest-xdist](https://pytest-xdist.readthedocs.io/en/stable/) is available (and recommended):

```bash
pip instal pytest-xdist
pytest -n auto --unit
```
This will spam and automated number of workers and run the testing suite. `auto` can be replace with an exact number of workers. More information on running the testing suite has been added to the contributing.md on this [branch](https://github.com/pybop-team/PyBOP/blob/86-bug-update-readmemd/CONTRIBUTING.md).
