### ISSUE TITLE
Initially Supported Models

### ISSUE THREAD

**Issue by BradyPlanden** [pybop-team/PyBOP#7]
Issue to discuss the selection of the initially supported models. Potential starting points include:

- Equivalent Circuit Models (ECM)
- Equivalent Hydraulic Model (EHM)
- Single Particle Model with Electrolyte (SPMe)

**Comment by martinjrobins** [comment]
How much freedom are we giving the user in terms of models? It seems a bit restrictive to say that you can only use "our" models.... I presume we want a user to be able to provide their own model? (see also my comment on #8)

**Comment by BradyPlanden** [comment]
> How much freedom are we giving the user in terms of models?

I think it might best to have tiered support for existing PyBaMM models. If we can provide examples & workflows (#10) for the above models (plus any others that might come out of this issue) initially, without removing functionality for other PyBaMM models that would be ideal. That would then allow users to continue with alternative models while we build _official_ support.

> I presume we want a user to be able to provide their own model?

Looking at your comment on #8, I think this is probably an direction we need to decide on early. To clarify before we get too far into it, we are discussing enabling support for user who want to define `self.rhs` in the PyBaMM model class, yeah? Probably best to create another issue for this..

**Comment by brosaplanella** [comment]
The way we handle this in pbparam is that the user needs to provide a simulation that runs (simulation = model + parameters + discretisation + solver ...). Of course, we have PyBaMM models in mind but this approach also allows user-defined models as long as they can work within the PyBaMM Simulation class.
