### ISSUE TITLE
Custom model structures

### ISSUE THREAD

**Issue by BradyPlanden** [pybop-team/PyBOP#89]
### Feature description

Provide an example of modifying or constructing an new `model.pybamm_model` structure. This issue provides a step towards #3.

**Comment by NicolaCourtier** [comment]
Does the addition of a standalone model (see [model.py](https://github.com/pybop-team/PyBOP/blob/develop/examples/standalone/model.py)) address this issue?

**Comment by BradyPlanden** [comment]
The addition of the `WeppnerHuggins` implementation can close this issue out.
