### ISSUE TITLE
Sensitivity analysis

### ISSUE THREAD

**Issue by davidhowey** [pybop-team/PyBOP#9]
We might consider including basic sensitivity analysis in PyBOP. This is already in PyBaMM so it would make sense to call and use the existing methods as a sanity check before going deeper on estimating parameters from data, perhaps as an initial stage in a workflow. What do you think @martinjrobins ?

**Comment by martinjrobins** [comment]
Sure, PyBaMM gives you dv/dp_i for each timepoint i, where v is a variable derived from the state vector y ($v = f(y)$), and p is a parameter of the model ($y = g(p)$. Is this issue about using these sensitivities to calculate addiitonal quantities of interest (e.g. curvature and confidance intervals around best fit points)?

**Comment by BradyPlanden** [comment]
Closing this issue as sensitivity support was added in #80.
